version: '3.9'

services:
  django:
    build: .
    container_name: django_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=website.settings
    entrypoint: ["/app/docker-entrypoint.sh"]
